name: Create Release

on:
  push:
    tags:
      - 'v*'
      - 
permissions:
  contents: write
  packages: write
  releases: write
  
jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore SpellingChecker.sln
    
    - name: Build
      run: dotnet build SpellingChecker.sln --configuration Release --no-restore
    
    - name: Publish
      run: dotnet publish SpellingChecker/SpellingChecker.csproj -c Release -r win-x64 --self-contained -p:PublishSingleFile=true -o ./publish
    
    - name: Create release ZIP
      run: |
        Compress-Archive -Path ./publish/SpellingChecker.exe, README.md, LICENSE, CONFIG.md, QUICKSTART.md -DestinationPath SpellingChecker-${{ github.ref_name }}-win-x64.zip
      shell: pwsh
    
    - name: Create Release with GitHub CLI
      run: |
        $releaseBody = @"
        ## SpellingChecker ${{ github.ref_name }}
        
        AI-powered spelling correction and translation tool for Windows.
        
        ### Installation
        1. Download ``SpellingChecker-${{ github.ref_name }}-win-x64.zip``
        2. Extract the ZIP file
        3. Run ``SpellingChecker.exe``
        4. Configure your OpenAI API key in Settings
        
        ### Features
        - AI-powered spelling and grammar correction
        - Korean-English translation
        - Global hotkeys (Ctrl+Shift+Alt+Y for correction, Ctrl+Shift+Alt+T for translation)
        - System tray integration
        - Usage statistics tracking
        
        See [CHANGELOG.md](https://github.com/trollgameskr/SpellingChecker/blob/main/CHANGELOG.md) for full release notes.
        "@
        
        gh release create ${{ github.ref_name }} `
          SpellingChecker-${{ github.ref_name }}-win-x64.zip `
          --title "SpellingChecker ${{ github.ref_name }}" `
          --notes "$releaseBody"
      shell: pwsh
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
